baseurl = "/"
title = "anotherblog"
languageCode = "en-us"
paginate = "3" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Ann Huang"
  bio = "Just an ordinary potato living in the land of potatoes striving for some extraordinary experiences ðŸ‡©ðŸ‡ª"
  avatar = "img/avatar.png"

[Params.widgets.social]
  twitter = "annnhuang"
  email = "ann.huang9419@gmail.com"
  github = "annnhuang"
  instagram = "annnhuang"

[Params]
  description = "Ann Huang's Personal blog about everything" # Description of your site
  opengraph = true
  twitter_cards = true
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "docs"]

[Params.logo]
  subtitle = "just another site" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)